### ISSUE TITLE
How do I map a key to open up the diagnostics popup?

### ISSUE THREAD

**Issue by sbromberger** [haorenW1025/diagnostic-nvim#14]
Thanks so much for this plugin. It really fixes a bunch of issues with the default lsp config.

I'd like the equivalent of
```
nnoremap <silent> gh    <cmd>lua vim.lsp.util.show_line_diagnostics()<CR>
```
since this doesn't appear to work any more. Is there a way to do this?

**Comment by gbrlsnchs** [comment]
I use the following:
```viml
command! -buffer -nargs=0 LspShowLineDiagnostics lua require'jumpLoc'.openLineDiagnostics()
nnoremap <buffer><silent> <C-h> <Cmd>LspShowLineDiagnostics<CR>
```

**Comment by sbromberger** [comment]
Thanks for this!

**Comment by haorenW1025** [comment]
Thanks @gbrlsnchs for the example config, you can use the code for now. `vim.lsp.util.show_line_diagnostics()` is not working because in order to get some of my work done, I have to overwrite a bunch of stuff. But the bulit-in LSP have evolved a lot since I created this plugins, so many of the workaround should be rebundant for now. I'll try to resolve this in my spare time and see if I can get `vim.lsp.util.show_line_diagnostics()` work as it is:)

**Comment by haorenW1025** [comment]
The default ` vim.lsp.util.show_line_diagnostics()` should be working now, please update and check.

**Comment by sbromberger** [comment]
Thanks! Confirmed working. Appreciate the quick fix.
