### ISSUE TITLE
Hover behavior: {Prev,Next}Diagnostic vs jumping to location list 

### ISSUE THREAD

**Issue by mjlbach** [haorenW1025/diagnostic-nvim#5]
This plugin is great! I've removed some of my own custom overrides of nvim callbacks in favor of this. One thing I've noticed is that the location list is populated with diagnostics, however, the behavior is different if one jumps to a location list item vs using the built-in {Prev, Next}Diagnostic functions. I'm wondering if this is intentional, as only the latter triggers the hover (with printing of the diagnostics in a floating window).

**Comment by haorenW1025** [comment]
Yeah that's the expected behavior. I use location list to jump around, so when you're using {Prev, Next}Diagnostic you're actually using location list(but it automatically find the nearest location and jump there for you) and it'll open up line diagnostic. It'll be much harder to track whenever user has used location list to jump around and open line diagnostic for them. Also I've never used the location list since {Prev, Next}Diagnostic is more intuitive for me.
