### ISSUE TITLE
statusline and generic namespacing

### ISSUE THREAD

**Issue by grantmacken** [haorenW1025/diagnostic-nvim#6]
Thanks for the plugin.  I was about to attempt a  lsp diagnostic statusline with Error and Warn count.
The nvim vim.lsp help has an example, but since I am using diagnostic, 
I thought I would see what was available, and found
```
print(vim.inspect(require('util').buf_diagnostics_count('Hint')))
```
This will do the trick,  but it highlights the namespace problem.
'util' is pretty generic module name and I see the completions plugin has  a 'utilty' module

I think these lua modules should be namespaced to their main module,
either by renaming  `util.lua` => `diagnostic_util.lua` or like  'neovim/nvim-lsp'
 a child 'diagnostic' dir so you can go `require('diagnostic.util')`

**Comment by haorenW1025** [comment]
Yeah that's better, I'll change it to `diagnostic/util.lua`

Also note that almost everything from `util.lua` is copied from neovim's source code, some of them was modified a little bit to fit the usage of this plugins. For the `buf_diagnostics_count` function is just the same(I have to copied it out because I've modifed some local function of neovim's source cod). I've found out when using `buf_diagnostics_count` in statusline, the CPU usage will be very high, so I recommend not to use it. I'm working on another solution which I'll remember the diagnostic count in `diagnostic.lua` in every callback. So getting diagnostic count is just getting a variable, which I suppose will ease the high CPU problem. I'm still working on that though, will mention you when I finish it!
